### PR TITLE
prompt.sh

### PR DESCRIPTION
**Pull request by foundjem**
The use of /home/$USER is causing a problem to some systems, for example, some system would prefer /Users/$USER or ~/ for the home directory; line 18 -- 'styles_dir="/home/$USER/.fancy-git/prompt_styles" ' (on the other hand, /home/$USER doesn't really seat well). It give error = " NO SUCH DIRECTORY"

### CODE REVIEW

**Comment by foundjem** [comment]
I changed line 18 of the prompt.sh file, which was causing a problem of a relative path for the home user.

**Comment by diogocavilha** [comment]
Thank you so much @foundjem for contributing with the Fancygit project.

I'm so sorry for having that path hard coded, it has been tested in a Debian like system and a Mac Mojave only. What's yours?

If you allow me some suggestion in order to add more compatibility on that part of code, maybe the existence of that path should be checked so.

**Example:**

Instead of:

```bash
styles_dir="/Users/$USER/.fancy-git/prompt_styles"
```

Maybe we could have:

```bash
styles_dir="/home/$USER/.fancy-git/prompt_styles"

if [ ! -d "$styles_dir" ]; then
    styles_dir="/Users/$USER/.fancy-git/prompt_styles"
fi
```

What do you think of it? 
This ways it keeps working for `/home/$USER`, but, in case it doesn't exist, it goes for `/User/$USER`.

Maybe, having a specific fallback path for a default style would be even a better solution, but the solution above solves the problem for you and for those who have a `/home/$USER` path.

**Comment by foundjem** [comment]
Hell,
Thanks for reaching out, 

> On Nov 12, 2018, at 4:22 PM, Diogo Alexsander Cavilha <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> Thank you so much @foundjem <https://github.com/foundjem> for contributing with the Fancygit project.
> 
> I'm so sorry for having that path hard coded, it has been tested in a Debian like system and a Mac Mojave only. What's yours?
> 
> If you allow me some suggestion in order to add more compatibility on that part of code, maybe the existence of that path should be checked so.
> 
> Example:
> 
> Instead of:
> 
> styles_dir="/Users/$USER/.fancy-git/prompt_styles"
> Maybe we could have:
> 
> 
Yes this seems to make sense on my opinion 
> styles_dir="/home/$USER/.fancy-git/prompt_styles"
> 
> if [ ! -d "$styles_dir" ]; then
>     styles_dir="/Users/$USER/.fancy-git/prompt_styles"
> fi
> What do you think of it?
> This ways it keeps working for /home/$USER, but, in case it doesn't exist, it goes for /User/$USER.
> 
> 
Sure, it will work!
> Maybe, having a specific fallback path for a default style would be even a better solution, but the solution above solves the problem for you and for those who have a /home/$USER path.
> 
> 
OK let’s go with this changes and see how it goes. Once more thanks



Armstrong

**Comment by diogocavilha** [comment]
Hello, @foundjem 

Do you want me to implement those changes?

**Pull request merged**
