### PR TITLE
Modify readme to reflect config change

### PR DESCRIPTION
**Pull request by MarvinKweyu**
Add `path-enable` and `path-disable` options.

### CODE REVIEW

**Comment by diogocavilha** [comment]
Hello @MarvinKweyu 

Thank you for your PR. I appreciate that.

**Comment by MarvinKweyu** [comment]
Hey @diogocavilha . I got an idea or two on improving the display of some git messages. However, I was wondering whether or not my pull would make it a necessary need to enable and disable capabilities just like the full path option.

**Comment by diogocavilha** [comment]
Huumm, I see!

I haven't done that because this way I wouldn't be able to use the same function in order to enable/disable capabilities. At least, I wouldn't be able to use the same function without using lots of `if` statements to show a proper message depending on the capability.

But, go on with your ideia please, I'd like to see what's on your mind!

**Comment by diogocavilha** [comment]
Miss understanding here.

Now I got what you mean.

[PR](https://github.com/diogocavilha/fancy-git/pull/51)

**Pull request merged**
