### PR TITLE
Add prompt time

### PR DESCRIPTION
**Pull request by jtrupina**
This PR ads additional prompt for current time in front of prompt for user@host which is configurable meaning it can be turned on/off by your preference (by setting `show-time` to either `true` or `false`). It is applied to all themes available. The prompt for current time has same stylish settings as prompt for user@host in every theme and I added square brackets as wrapper around time (like: `[20:21:12]`, check the screenshots below). Additionally, user can configure his preferred format of showing time by setting value for key `time_format` in `config.sh` file. Default time format is: `%H:%M:%S` but it can be overriden in `config-override.sh` file.

Under the hood it uses `date` shell command which is installed on most unix/linux distributions and macos by default.

The other idea could be that we have predefined time formats in `config.sh` for example:

```
//config.sh
local hour_minute_second_format

hour_minute_second_format=%H:%M:%S
```

and in `app_config` you could reference certain time format by descriptive variable name from `config.sh` like `time-format:hour_minute_second_format` but there are so many ways of formatting time and I am not sure is it really worth of listing them all. I would rather let user to define it's own time format in `config-override` which will override defaulted `time_format` in `config.sh`

#### default:

image

#### dark:

image

#### dark-col-double-line:

image

#### dark-double-line:

image

#### fancy-double-line:

image

#### human:

image

#### human-dark:

image

#### human-dark-single-line:

image

#### human-single-line:

image

#### light:

image

#### light-double-line:

image

#### simple:

image

#### simple-double-line:

image

### CODE REVIEW

**Comment by diogocavilha** [comment]
Wow!

Thank you @jtrupina, you did a good job here!

I'm so sorry because I know that maintaining many styles is getting harder once they work independently. It is good because we have a limited scope of running code, but in the other hand, we have too much repeated code, which rangs my gears because we could reuse some routines. 
I'm thinking on how to solve that problem already. Soon it'll be improved little by little.

Everything about the code you've done is ok for me.  
I'll ask you just to add a few more changes regarding to enable and disable this new feature. 

1.  Like, you can see that at the end of `commands.sh` file we kind of have a parameters parser. That would be great to have something like `--enable-time` and `--disable-time`, for example. As you can see, we already have some other similar parameters in order to enable or disable other FancyGit features.
2. After creating these parameters, you could also add them into the `fancygit-completion` file. This way we can use TAB key to auto complete these new FancyGit commands.
3. I'd ask you to add these commands into the `help.sh` file too, but I've just realized that the help text is a bit outdated, so, don't worry, I'll complete this step after your changes :grin:.

I really appreciate your attention and time for helping to improve FancyGit. Thank you man!

**Comment by jtrupina** [comment]
> Wow!
> 
> Thank you @jtrupina, you did a good job here!

No problem! Very happy to do it.

> 
> I'm so sorry because I know that maintaining many styles is getting harder once they work independently. It is good because we have a limited scope of running code, but in the other hand, we have too much repeated code, which rangs my gears because we could reuse some routines.
> I'm thinking on how to solve that problem already. Soon it'll be improved little by little.

Yeah, I totally understand you. Happy to hear about future potential improvements regarding code repetition. :)


> Everything about the code you've done is ok for me.
> I'll ask you just to add a few more changes regarding to enable and disable this new feature.
> 
> 1. Like, you can see that at the end of `commands.sh` file we kind of have a parameters parser. That would be great to have something like `--enable-time` and `--disable-time`, for example. As you can see, we already have some other similar parameters in order to enable or disable other FancyGit features.
> 2. After creating these parameters, you could also add them into the `fancygit-completion` file. This way we can use TAB key to auto complete these new FancyGit commands.
> 3. I'd ask you to add these commands into the `help.sh` file too, but I've just realized that the help text is a bit outdated, so, don't worry, I'll complete this step after your changes grin.

Thanks! It seems that I kinda forgot about CLI commands, help usage and tab completion so thanks of reminding me of that.

Regarding parameters parser in `command.sh` I added `--enable-show-time` and `--disable-show-time` so it's consistent with other naming like: `enable-show-user-at-machine`. 


> I really appreciate your attention and time for helping to improve FancyGit. Thank you man!

My pleasure!

**Comment by diogocavilha** [comment]
@jtrupina, thank you man.

All changes are ok now ;)

> Regarding parameters parser in command.sh I added --enable-show-time and --disable-show-time so it's consistent with other naming like: enable-show-user-at-machine.

Oh, yes, this is part of what's gonna be changed too. Soon these commands will change a bit. The word `show` is gonna be removed from them. But don't worry about that. Your PR is quite perfect. :)

**Comment by diogocavilha** [comment]
@all-contributors please add @jtrupina for code

**Pull request merged**
